/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StopsEditIF.java
 *
 * Created on 2009-06-17, 13:27:03
 */
package dach;

import dach.renderer.DistancesListRenderer;
import dach.renderer.StopsListCellRenderer;
import org.jdesktop.application.Action;
import ws.chojnacki.timetable.mapping.Distance;
import ws.chojnacki.timetable.mapping.GeoPoint;
import ws.chojnacki.timetable.mapping.Stop;
import ws.chojnacki.timetable.rxmldata.EntityFactory;

/**
 *
 * @author Pawel
 */
public class DistancesEditIF extends javax.swing.JInternalFrame implements DataAccessInterface {

    private EntityFactory ef;
    private WrapperModel stopsModel;
    private Distance editedDistance;

    /** Creates new form StopsEditIF */
    public DistancesEditIF() {
        initComponents();
        jList1.setCellRenderer(new DistancesListRenderer());
        fromStopCB.setRenderer(new StopsListCellRenderer());
        toStopCB.setRenderer(new StopsListCellRenderer());
        jPanel1.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        fromStopCB = new javax.swing.JComboBox();
        toStopCB = new javax.swing.JComboBox();
        highTrafTF = new javax.swing.JTextField();
        lowTrafTF = new javax.swing.JTextField();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setMaximizable(true);
        setResizable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(dach.DACHApp.class).getContext().getResourceMap(DistancesEditIF.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setName("jList1"); // NOI18N
        jScrollPane1.setViewportView(jList1);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(dach.DACHApp.class).getContext().getActionMap(DistancesEditIF.class, this);
        jButton1.setAction(actionMap.get("addElement")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        jButton2.setAction(actionMap.get("deleteItem")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setName("jSeparator1"); // NOI18N

        jButton4.setAction(actionMap.get("editItem")); // NOI18N
        jButton4.setName("jButton4"); // NOI18N

        jPanel1.setEnabled(false);
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jButton3.setAction(actionMap.get("saveElement")); // NOI18N
        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N

        jButton5.setAction(actionMap.get("cancelEdit")); // NOI18N
        jButton5.setText(resourceMap.getString("jButton5.text")); // NOI18N
        jButton5.setName("jButton5"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        fromStopCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        fromStopCB.setName("fromStopCB"); // NOI18N

        toStopCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        toStopCB.setName("toStopCB"); // NOI18N

        highTrafTF.setText(resourceMap.getString("highTrafTF.text")); // NOI18N
        highTrafTF.setName("highTrafTF"); // NOI18N

        lowTrafTF.setText(resourceMap.getString("lowTrafTF.text")); // NOI18N
        lowTrafTF.setName("lowTrafTF"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                        .addComponent(jButton5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lowTrafTF, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                            .addComponent(toStopCB, 0, 193, Short.MAX_VALUE)
                            .addComponent(fromStopCB, 0, 193, Short.MAX_VALUE)
                            .addComponent(highTrafTF, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fromStopCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(toStopCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(highTrafTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lowTrafTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton5))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addContainerGap())
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    public void setEntityFactory(EntityFactory ef) {
        this.ef = ef;
        this.stopsModel = new WrapperModel(ef, Distance.class);
        jList1.setModel(this.stopsModel);
        fromStopCB.setModel(new StopComboBoxModel(ef, Stop.class));
        toStopCB.setModel(new StopComboBoxModel(ef, Stop.class));
    }

    @Action
    public void deleteItem() {
        jPanel1.setVisible(false);
    }

    @Action
    public void editItem() {
        for (int i : jList1.getSelectedIndices()) {
            if (stopsModel.getElementAt(i).getClass().isAssignableFrom(Distance.class)) {
                Distance dist = (Distance) stopsModel.getElementAt(i);
                if (dist.getFromStop() != null) {
                    setEditPanel(dist.getFromStop(), dist.getToStop(), dist.getHighTraffic(), dist.getLowTraffic());
                } else {
                    highTrafTF.setText("" + dist.getHighTraffic());
                    lowTrafTF.setText("" + dist.getLowTraffic());
                //setEditPanel(dist.getName(), 0.0, 0.0);
                }
                jPanel1.setVisible(true);
                this.editedDistance = dist;
            }
            break;
        }

    }

    public void setEditPanel(Stop fromStop, Stop toStop, int highTraf, int lowTraf) {
        fromStopCB.setSelectedItem(fromStop);
        toStopCB.setSelectedItem(toStop);
        highTrafTF.setText("" + highTraf);
        lowTrafTF.setText("" + lowTraf);

    }

    @Action
    public void saveElement() {
        Stop fromStop = (Stop) fromStopCB.getSelectedItem();
        Stop toStop = (Stop) toStopCB.getSelectedItem();
        int highTraf = 1;
        int lowTraf = 1;
        try {
            highTraf = Integer.parseInt(highTrafTF.getText());
            lowTraf = Integer.parseInt(lowTrafTF.getText());
        } catch (NumberFormatException ex) {
            System.err.println("Banzai Integer!");
        }
        if (editedDistance == null) {
            editedDistance = new Distance(fromStop, toStop, highTraf, lowTraf);
            stopsModel.addElementAtTheEnd(editedDistance);
        } else {
            editedDistance.setFromStop(fromStop);
            editedDistance.setToStop(toStop);
            editedDistance.setHighTraffic(highTraf);
            editedDistance.setLowTraffic(lowTraf);
            stopsModel.change(editedDistance);
        }
        jPanel1.setVisible(false);

    }

    @Action
    public void addElement() {
        jPanel1.setVisible(true);
        highTrafTF.setText("1");
        lowTrafTF.setText("1");
        editedDistance = null;
    }

    @Action
    public void cancelEdit() {
        editedDistance = null;
        jPanel1.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox fromStopCB;
    private javax.swing.JTextField highTrafTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField lowTrafTF;
    private javax.swing.JComboBox toStopCB;
    // End of variables declaration//GEN-END:variables
}
