/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LinesEditIF.java
 *
 * Created on 2009-06-17, 12:09:22
 */
package dach;

import dach.renderer.DepartureListCellRender;
import dach.renderer.DeptTableCellRenderer;
import dach.renderer.LinesListCellRenderer;
import dach.renderer.StopsListCellRenderer;
import java.awt.Component;
import java.io.RandomAccessFile;
import java.text.DateFormat;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractListModel;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import javax.swing.ListModel;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.application.Action;
import ws.chojnacki.timetable.mapping.Departure;
import ws.chojnacki.timetable.mapping.Line;
import ws.chojnacki.timetable.mapping.Route;
import ws.chojnacki.timetable.mapping.Stop;
import ws.chojnacki.timetable.rxmldata.EntityFactory;
import ws.chojnacki.timetable.rxmldata.IdentifiedEntity;

/**
 *
 * @author Pawel
 */
public class LinesEditIF extends javax.swing.JInternalFrame implements DataAccessInterface {

    private EntityFactory ef;
    private WrapperModel linesModel;
    private Line editedLine;
    private WrapperModel stopsModel;
    private boolean weekSelected = false;
    private boolean saturdaySelected = false;
    private boolean holidaySelected = false;

    /** Creates new form LinesEditIF */
    public LinesEditIF() {
        initComponents();
        

        linesList.setCellRenderer(new LinesListCellRenderer());
        routeList.setCellRenderer(new StopsListCellRenderer());
        stopsCb.setRenderer(new StopsListCellRenderer());
        editPanel.setVisible(false);
        weekList.setCellRenderer(new DepartureListCellRender());
        saturdayList.setCellRenderer(new DepartureListCellRender());
        holidayList.setCellRenderer(new DepartureListCellRender());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        linesList = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        editPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        routeList = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        weekList = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        saturdayList = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        holidayList = new javax.swing.JList();
        stopsCb = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        timePanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        timeTf = new javax.swing.JTextField();
        legendTf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lineNameTf = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setMaximizable(true);
        setResizable(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(dach.DACHApp.class).getContext().getResourceMap(LinesEditIF.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setVisible(true);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        linesList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        linesList.setName("linesList"); // NOI18N
        jScrollPane1.setViewportView(linesList);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(dach.DACHApp.class).getContext().getActionMap(LinesEditIF.class, this);
        jButton1.setAction(actionMap.get("addElement")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        jButton2.setAction(actionMap.get("deleteElement")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setName("jSeparator1"); // NOI18N

        jButton3.setAction(actionMap.get("editElement")); // NOI18N
        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N

        editPanel.setName("editPanel"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        routeList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        routeList.setName("routeList"); // NOI18N
        jScrollPane2.setViewportView(routeList);

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        weekList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        weekList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        weekList.setFixedCellWidth(90);
        weekList.setName("weekList"); // NOI18N
        jScrollPane3.setViewportView(weekList);

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jScrollPane4.setName("jScrollPane4"); // NOI18N

        saturdayList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        saturdayList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        saturdayList.setFixedCellWidth(90);
        saturdayList.setName("saturdayList"); // NOI18N
        jScrollPane4.setViewportView(saturdayList);

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jScrollPane5.setName("jScrollPane5"); // NOI18N

        holidayList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        holidayList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        holidayList.setFixedCellWidth(90);
        holidayList.setName("holidayList"); // NOI18N
        jScrollPane5.setViewportView(holidayList);

        stopsCb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        stopsCb.setName("stopsCb"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jButton4.setAction(actionMap.get("stopAddElement")); // NOI18N
        jButton4.setText(resourceMap.getString("jButton4.text")); // NOI18N
        jButton4.setName("jButton4"); // NOI18N

        jButton5.setAction(actionMap.get("stopRemoveElement")); // NOI18N
        jButton5.setText(resourceMap.getString("jButton5.text")); // NOI18N
        jButton5.setName("jButton5"); // NOI18N

        timePanel.setName("timePanel"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        timeTf.setText(resourceMap.getString("timeTf.text")); // NOI18N
        timeTf.setName("timeTf"); // NOI18N

        legendTf.setText(resourceMap.getString("legendTf.text")); // NOI18N
        legendTf.setName("legendTf"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        jButton13.setAction(actionMap.get("saveDeparture")); // NOI18N
        jButton13.setText(resourceMap.getString("jButton13.text")); // NOI18N
        jButton13.setName("jButton13"); // NOI18N

        javax.swing.GroupLayout timePanelLayout = new javax.swing.GroupLayout(timePanel);
        timePanel.setLayout(timePanelLayout);
        timePanelLayout.setHorizontalGroup(
            timePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(timePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(timeTf, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGroup(timePanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(legendTf, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                    .addComponent(jButton13, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        timePanelLayout.setVerticalGroup(
            timePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(timePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(legendTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton13)
                .addContainerGap())
        );

        jButton6.setAction(actionMap.get("addWeek")); // NOI18N
        jButton6.setText(resourceMap.getString("jButton6.text")); // NOI18N
        jButton6.setName("jButton6"); // NOI18N

        jButton7.setAction(actionMap.get("addSaturday")); // NOI18N
        jButton7.setText(resourceMap.getString("jButton7.text")); // NOI18N
        jButton7.setName("jButton7"); // NOI18N

        jButton8.setAction(actionMap.get("addHoliday")); // NOI18N
        jButton8.setText(resourceMap.getString("jButton8.text")); // NOI18N
        jButton8.setName("jButton8"); // NOI18N

        jButton9.setAction(actionMap.get("removeWeek")); // NOI18N
        jButton9.setText(resourceMap.getString("jButton9.text")); // NOI18N
        jButton9.setName("jButton9"); // NOI18N

        jButton10.setAction(actionMap.get("removeSaturday")); // NOI18N
        jButton10.setText(resourceMap.getString("jButton10.text")); // NOI18N
        jButton10.setName("jButton10"); // NOI18N

        jButton11.setAction(actionMap.get("removeHoliday")); // NOI18N
        jButton11.setText(resourceMap.getString("jButton11.text")); // NOI18N
        jButton11.setName("jButton11"); // NOI18N

        jButton12.setAction(actionMap.get("saveLine")); // NOI18N
        jButton12.setText(resourceMap.getString("jButton12.text")); // NOI18N
        jButton12.setName("jButton12"); // NOI18N

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        lineNameTf.setText(resourceMap.getString("lineNameTf.text")); // NOI18N
        lineNameTf.setName("lineNameTf"); // NOI18N

        jButton14.setAction(actionMap.get("cancelLine")); // NOI18N
        jButton14.setText(resourceMap.getString("jButton14.text")); // NOI18N
        jButton14.setName("jButton14"); // NOI18N

        javax.swing.GroupLayout editPanelLayout = new javax.swing.GroupLayout(editPanel);
        editPanel.setLayout(editPanelLayout);
        editPanelLayout.setHorizontalGroup(
            editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE))
                    .addGroup(editPanelLayout.createSequentialGroup()
                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton6)
                            .addGroup(editPanelLayout.createSequentialGroup()
                                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, editPanelLayout.createSequentialGroup()
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                        .addComponent(jButton9, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGroup(editPanelLayout.createSequentialGroup()
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton7)
                                    .addComponent(jLabel3)
                                    .addComponent(jButton10)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8)
                            .addComponent(jLabel4)
                            .addComponent(jButton11))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(stopsCb, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(timePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addComponent(lineNameTf, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPanelLayout.createSequentialGroup()
                        .addComponent(jButton12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton14)))
                .addContainerGap())
        );
        editPanelLayout.setVerticalGroup(
            editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPanelLayout.createSequentialGroup()
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editPanelLayout.createSequentialGroup()
                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6)
                            .addComponent(jButton7)
                            .addComponent(jButton8)))
                    .addGroup(editPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(stopsCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addGap(29, 29, 29)
                        .addComponent(timePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lineNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jButton10)
                    .addComponent(jButton11)
                    .addComponent(jButton14)
                    .addComponent(jButton12))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(editPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    public void setEntityFactory(EntityFactory ef) {
        this.ef = ef;
        linesModel = new WrapperModel(ef, Line.class);
        linesList.setModel(linesModel);
        stopsCb.setModel(new StopComboBoxModel(ef, Stop.class));
    }

    @Action
    public void deleteElement() {
        for (int index : linesList.getSelectedIndices()) {
            linesModel.removeElementAt(index);
            linesList.setSelectedIndex(-1);
            break;

        }
    }

    @Action
    public void editElement() {
        for (Object object : linesList.getSelectedValues()) {
            editedLine = (Line) object;

            stopsCb.setModel(new StopComboBoxModel(ef, Stop.class));
            weekList.setModel(new DepartureListModel(new ArrayList(editedLine.getDeparturesWeek())));
            saturdayList.setModel(new DepartureListModel(new ArrayList(editedLine.getDeparturesSaturday())));
            holidayList.setModel(new DepartureListModel(new ArrayList(editedLine.getDeparturesHoliday())));
            lineNameTf.setText(editedLine.getName());
            if (editedLine.getRoute() == null) {
                editedLine.setRoute(new Route());
            }

            routeList.setModel(new DepartureListModel(new ArrayList(editedLine.getRoute().getStops())));
            editPanel.setVisible(true);
            timePanel.setVisible(false);

            break;
        }

    }

    @Action
    public void addElement() {
        editPanel.setVisible(true);
        editedLine = null;
        stopsCb.setModel(new StopComboBoxModel(ef, Stop.class));
        weekList.setModel(new DepartureListModel(new ArrayList()));
        saturdayList.setModel(new DepartureListModel(new ArrayList()));
        holidayList.setModel(new DepartureListModel(new ArrayList()));
        lineNameTf.setText("New route!!!");
        routeList.setModel(new DepartureListModel(new ArrayList()));
        timePanel.setVisible(false);
    }

    @Action
    public void stopAddElement() {
        boolean isSelected = false;
        for (int i : routeList.getSelectedIndices()) {
            isSelected = true;
            ((DepartureListModel) routeList.getModel()).addElementAt(i, stopsCb.getSelectedItem());
            break;
        }
        if (!isSelected) {
            ((DepartureListModel) routeList.getModel()).addElement(stopsCb.getSelectedItem());
        }
    }

    @Action
    public void stopRemoveElement() {
        for (int i : routeList.getSelectedIndices()) {
            ((DepartureListModel) routeList.getModel()).removeElementAt(i);

        }
    }

    @Action
    public void saveLine() {
        boolean wasNew = false;
        if (editedLine == null) {
            editedLine = new Line();
            editedLine.setRoute(new Route());
            wasNew = true;
            editedLine.setName(lineNameTf.getText());
        }
        editedLine.setDeparturesHoliday(((DepartureListModel) holidayList.getModel()).getList());
        editedLine.setDeparturesWeek(((DepartureListModel) weekList.getModel()).getList());
        editedLine.setDeparturesSaturday(((DepartureListModel) saturdayList.getModel()).getList());
        editedLine.setRoute(new Route());
        editedLine.getRoute().setStops(((DepartureListModel) routeList.getModel()).getList());
        if (wasNew) {
            linesModel.addElementAtTheEnd(editedLine);
        } else
            linesModel.change(editedLine);
        editedLine = null;
        editPanel.setVisible(false);
    }

    @Action
    public void cancelLine() {
        editPanel.setVisible(false);
        editedLine = null;
    }

    @Action
    public void addWeek() {
        timePanel.setVisible(true);
        this.holidaySelected = false;
        this.weekSelected = true;
        this.saturdaySelected = false;
        timeTf.setText("00:00");
        legendTf.setText("");

    }

    @Action
    public void addHoliday() {
        timePanel.setVisible(true);
        this.holidaySelected = true;
        this.weekSelected = false;
        this.saturdaySelected = false;
        timeTf.setText("00:00");
        legendTf.setText("");

    }

    @Action
    public void addSaturday() {
        timePanel.setVisible(true);
        this.holidaySelected = false;
        this.weekSelected = false;
        this.saturdaySelected = true;
        timeTf.setText("00:00");
        legendTf.setText("");

    }

    @Action
    public void removeWeek() {
        for (int i : weekList.getSelectedIndices()) {
            ((DepartureListModel) weekList.getModel()).removeElementAt(i);
            break;
        }
    }

    @Action
    public void removeSaturday() {
        for (int i : saturdayList.getSelectedIndices()) {
            ((DepartureListModel) saturdayList.getModel()).removeElementAt(i);
            break;
        }
    }

    @Action
    public void removeHoliday() {
        for (int i : holidayList.getSelectedIndices()) {
            ((DepartureListModel) holidayList.getModel()).removeElementAt(i);
            break;
        }
    }

    @Action
    public void saveDeparture() {
        Departure enteredDeparture = new Departure();
        try {
            enteredDeparture.setTime(DateFormat.getTimeInstance(DateFormat.SHORT).parse(timeTf.getText()));
        } catch (ParseException ex) {
            System.err.println("Booboo time");

        //Logger.getLogger(LinesEditIF.class.getName()).log(Level.SEVERE, null, ex);
        }
        enteredDeparture.setLegend(legendTf.getText());
        if (weekSelected) {
            if (weekList.isSelectionEmpty()) {
                if (enteredDeparture.getTime() == null) {
                    enteredDeparture.setTime(new Date(0));
                }
                ((DepartureListModel) weekList.getModel()).addElement(enteredDeparture);
            } else {
                for (int i : weekList.getSelectedIndices()) {
                    Departure lastDeparture = (Departure) ((DepartureListModel) weekList.getModel()).getElementAt(i);

                    if (enteredDeparture.getTime() == null) {
                        enteredDeparture.setTime(lastDeparture.getTime());
                    }
                    ((DepartureListModel) weekList.getModel()).addElementAt(i, enteredDeparture);
                    break;
                }
            }
        } else if (saturdaySelected) {
            if (saturdayList.isSelectionEmpty()) {
                if (enteredDeparture.getTime() == null) {
                    enteredDeparture.setTime(new Date(0));
                }
                ((DepartureListModel) saturdayList.getModel()).addElement(enteredDeparture);
            } else {
                for (int i : saturdayList.getSelectedIndices()) {
                    Departure lastDeparture = (Departure) ((DepartureListModel) saturdayList.getModel()).getElementAt(i);

                    if (enteredDeparture.getTime() == null) {
                        enteredDeparture.setTime(lastDeparture.getTime());
                    }
                    ((DepartureListModel) saturdayList.getModel()).addElementAt(i, enteredDeparture);
                    break;
                }
            }
        } else if (holidaySelected) {
            if (holidayList.isSelectionEmpty()) {
                if (enteredDeparture.getTime() == null) {
                    enteredDeparture.setTime(new Date(0));
                }
                ((DepartureListModel) holidayList.getModel()).addElement(enteredDeparture);
            } else {
                for (int i : holidayList.getSelectedIndices()) {
                    Departure lastDeparture = (Departure) ((DepartureListModel) holidayList.getModel()).getElementAt(i);

                    if (enteredDeparture.getTime() == null) {
                        enteredDeparture.setTime(lastDeparture.getTime());
                    }
                    ((DepartureListModel) holidayList.getModel()).addElementAt(i, enteredDeparture);
                    break;
                }
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel editPanel;
    private javax.swing.JList holidayList;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField legendTf;
    private javax.swing.JTextField lineNameTf;
    private javax.swing.JList linesList;
    private javax.swing.JList routeList;
    private javax.swing.JList saturdayList;
    private javax.swing.JComboBox stopsCb;
    private javax.swing.JPanel timePanel;
    private javax.swing.JTextField timeTf;
    private javax.swing.JList weekList;
    // End of variables declaration//GEN-END:variables
}
